//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCarBikeRentalSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineCarBikeRentalDBEntities : DbContext
    {
        public OnlineCarBikeRentalDBEntities()
            : base("name=OnlineCarBikeRentalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAboutU> tblAboutUs { get; set; }
        public virtual DbSet<tblBikeCar> tblBikeCars { get; set; }
        public virtual DbSet<tblBikeCarRecord> tblBikeCarRecords { get; set; }
        public virtual DbSet<tblBooking> tblBookings { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblComment> tblComments { get; set; }
        public virtual DbSet<tblContact> tblContacts { get; set; }
        public virtual DbSet<tblCustomerRecord> tblCustomerRecords { get; set; }
        public virtual DbSet<tblDriver> tblDrivers { get; set; }
        public virtual DbSet<tblFaqHeading> tblFaqHeadings { get; set; }
        public virtual DbSet<tblFaqQA> tblFaqQAs { get; set; }
        public virtual DbSet<tblHelpDesk> tblHelpDesks { get; set; }
        public virtual DbSet<tblMenu> tblMenus { get; set; }
        public virtual DbSet<tblPackageContent> tblPackageContents { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
        public virtual DbSet<tblRentalContent> tblRentalContents { get; set; }
        public virtual DbSet<tblServicesContent> tblServicesContents { get; set; }
        public virtual DbSet<tblServiceSection> tblServiceSections { get; set; }
        public virtual DbSet<tblSlider> tblSliders { get; set; }
        public virtual DbSet<tblStock> tblStocks { get; set; }
        public virtual DbSet<tblSubMenu> tblSubMenus { get; set; }
        public virtual DbSet<tblTestimonial> tblTestimonials { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblVendor> tblVendors { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
