//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCarBikeRentalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAboutU
    {
        public int AboutUsId { get; set; }
        public string SubHeadingParagraph { get; set; }
        public string Content { get; set; }
        public string Image { get; set; }
        public string Icon { get; set; }
        public string CardHeading { get; set; }
        public string CardParagraph { get; set; }
    }
}
