//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCarBikeRentalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBikeCar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBikeCar()
        {
            this.tblBikeCarRecords = new HashSet<tblBikeCarRecord>();
            this.tblBookings = new HashSet<tblBooking>();
            this.tblStocks = new HashSet<tblStock>();
        }
    
        public int VehicleId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string Bike_CarName { get; set; }
        public string EngieneCC { get; set; }
        public Nullable<int> PricePerHour { get; set; }
        public Nullable<int> PricePerDay { get; set; }
        public Nullable<int> PricePerWeek { get; set; }
        public Nullable<int> PricePermonth { get; set; }
        public string FuelUsed { get; set; }
        public string SmallImage { get; set; }
        public string LargeImgae { get; set; }
    
        public virtual tblVendor tblVendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBikeCarRecord> tblBikeCarRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBooking> tblBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStock> tblStocks { get; set; }
    }
}
