//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCarBikeRentalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBikeCarRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBikeCarRecord()
        {
            this.tblCustomerRecords = new HashSet<tblCustomerRecord>();
        }
    
        public int BikeCarRecordId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public string NoPlate { get; set; }
        public string EngieneNo { get; set; }
    
        public virtual tblBikeCar tblBikeCar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerRecord> tblCustomerRecords { get; set; }
    }
}
