//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCarBikeRentalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomerRecord()
        {
            this.tblPayments = new HashSet<tblPayment>();
        }
    
        public int CustomerRecordId { get; set; }
        public Nullable<int> BookingId { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public Nullable<int> BikeCarRecordId { get; set; }
        public string CitizenshipNo { get; set; }
        public string Photo { get; set; }
        public string LicenseNo { get; set; }
    
        public virtual tblBikeCarRecord tblBikeCarRecord { get; set; }
        public virtual tblBooking tblBooking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayment> tblPayments { get; set; }
    }
}
