//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCarBikeRentalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStock
    {
        public int StockId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<int> TotalBike_Car { get; set; }
    
        public virtual tblBikeCar tblBikeCar { get; set; }
    }
}
